language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
addons:
  chrome: stable
before-script:
  - wget https://chromedriver.storage.googleapis.com/index.html?path=84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/lib/
  - export CHROME_BIN=chromium-browser
script:
  - python prajavani-dl-chrome.py srsamartha@gmail.com
